version: '3.4'

services:
  officemanager.api:
   container_name: officemanager.api
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Default=Data Source=officemanagerdb;Initial Catalog=OfficeManager_DB;User Id=sa;Password=Admin#123"
      - "CacheSettings:RedisURL=rediscache"
      - "CacheSettings:Port=6379"
      - "CacheSettings:PreferRedis=true"
   ports:
      - "10000:80"