version: '3.4'

services:
  rediscache:
    image: redis
    container_name: rediscache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
  officemanager.api:
    image: ${DOCKER_REGISTRY-}officemanagerapi
    build:
      context: .
      dockerfile: src\OfficeManager.API\Dockerfile
  portainer:
    image: portainer/portainer-ce
  
volumes:
  portainer_data:
  redis_volume:
