version: '3.4'

services:
  rediscache:
    image: redis
    container_name: rediscache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data

  officemanagerdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: officemanagerdb
    environment:
        SA_PASSWORD: "Admin#123"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  officemanager.api:
    image: ${DOCKER_REGISTRY-}officemanagerapi
    build:
      context: .
      dockerfile: src\OfficeManager.API\Dockerfile
    depends_on:
      - officemanagerdb
  
volumes:
  redis_volume: