version: '3.4'

services:
  watchdogdb:
    container_name: watchdogdb
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=Admin#123
     - POSTGRES_DB=OfficeManagerWatchDogDb
    restart: always
    ports:
     - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
     - PGADMIN_DEFAULT_PASSWORD=Admin#123
    restart: always
    ports:
     - "5050:80"
    volumes:
     - pgadmin_data:/root/.pgadmin

  officemanager.api:
    container_name: officemanager.api
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - "ConnectionStrings:Default=Data Source=officemanagerdb;Initial Catalog=OfficeManager_DB;User Id=sa;Password=Admin#123"
     - "ConnectionStrings:PostgreSqlConnection=Server=watchdogdb;Port=5432;Database=OfficeManagerWatchDogDb;User Id=admin;Password=Admin#123;"
     - "CacheSettings:RedisURL=rediscache"
     - "CacheSettings:Port=6379"
     - "CacheSettings:PreferRedis=true"
     - "WatchDogSettings:Username=admin"
     - "WatchDogSettings:Password=Admin#123"
    ports:
     - "10000:80"